name: Build and Publish

on:
  push:

jobs:
  container:
    name: Build and Publish Rock Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Build Assets
        run: |
          yarn install
          yarn run build-css

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Checkout Rockcraft
        uses: actions/checkout@v2
        with:
          repository: weiiwang01/rockcraft
          path: rockcraft

      - name: Build rockcraft
        working-directory: ./rockcraft
        run: |
          sudo snap install snapcraft --classic
          snapcraft --use-lxd
          sudo snap install rockcraft*.snap --classic --dangerous

      - name: Build Rock image
        run: |
          export ROCKCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS=true
          rockcraft pack
      - name: Publish Rock Image
        run: >-
          skopeo --insecure-policy copy 
            oci-archive:assets-canonical-com_0.1_amd64.rock
            docker://ghcr.io/${{ github.repository_owner }}/assets.canonical.com:$(git rev-parse --short HEAD)
            --dest-creds "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}"
